# 应用名
spring:
  application:
    name: mall_framework

# 服务启动端口号和IP
server:
  port: 8080
  address: 127.0.0.1

# 数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wggt_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 0405
