# 服务启动端口号和IP
server:
  port: 8080
  address: 127.0.0.1

# Spring相关
spring:
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/wggt_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    # yml解析以0，0x，0b开头的数字会自动按8，16，2进制解析，要加''或者""来解决
    password: '0405'
  # 应用名
  application:
    name: mall_framework
  # redis连接信息
  data:
    redis:
      host: 192.168.114.129
      port: 6379

# SpringDoc相关
springdoc:
  # 文档版本
  version: '1.0'
  # 开发服务器url
  dev-url: 'http://localhost:8080'