package com.wggt.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   购物车表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table oms_cart_item
 */
public class OmsCartItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sku_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long productSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.member_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long memberId;

    /**
     * Database Column Remarks:
     *   购买数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.quantity
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   添加到购物车的价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.price
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   商品主图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_pic
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String productPic;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_name
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   商品副标题（卖点）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sub_title
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String productSubTitle;

    /**
     * Database Column Remarks:
     *   商品sku条码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sku_code
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String productSkuCode;

    /**
     * Database Column Remarks:
     *   会员昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.member_nickname
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String memberNickname;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.create_date
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.modify_date
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Date modifyDate;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.delete_status
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Integer deleteStatus;

    /**
     * Database Column Remarks:
     *   商品分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_category_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_brand
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sn
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String productSn;

    /**
     * Database Column Remarks:
     *   商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_attr
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private String productAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_cart_item
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.id
     *
     * @return the value of oms_cart_item.id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.id
     *
     * @param id the value for oms_cart_item.id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_id
     *
     * @return the value of oms_cart_item.product_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_id
     *
     * @param productId the value for oms_cart_item.product_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sku_id
     *
     * @return the value of oms_cart_item.product_sku_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sku_id
     *
     * @param productSkuId the value for oms_cart_item.product_sku_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.member_id
     *
     * @return the value of oms_cart_item.member_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.member_id
     *
     * @param memberId the value for oms_cart_item.member_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.quantity
     *
     * @return the value of oms_cart_item.quantity
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.quantity
     *
     * @param quantity the value for oms_cart_item.quantity
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.price
     *
     * @return the value of oms_cart_item.price
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.price
     *
     * @param price the value for oms_cart_item.price
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_pic
     *
     * @return the value of oms_cart_item.product_pic
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_pic
     *
     * @param productPic the value for oms_cart_item.product_pic
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_name
     *
     * @return the value of oms_cart_item.product_name
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_name
     *
     * @param productName the value for oms_cart_item.product_name
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sub_title
     *
     * @return the value of oms_cart_item.product_sub_title
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getProductSubTitle() {
        return productSubTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sub_title
     *
     * @param productSubTitle the value for oms_cart_item.product_sub_title
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductSubTitle(String productSubTitle) {
        this.productSubTitle = productSubTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sku_code
     *
     * @return the value of oms_cart_item.product_sku_code
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getProductSkuCode() {
        return productSkuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sku_code
     *
     * @param productSkuCode the value for oms_cart_item.product_sku_code
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductSkuCode(String productSkuCode) {
        this.productSkuCode = productSkuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.member_nickname
     *
     * @return the value of oms_cart_item.member_nickname
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getMemberNickname() {
        return memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.member_nickname
     *
     * @param memberNickname the value for oms_cart_item.member_nickname
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setMemberNickname(String memberNickname) {
        this.memberNickname = memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.create_date
     *
     * @return the value of oms_cart_item.create_date
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.create_date
     *
     * @param createDate the value for oms_cart_item.create_date
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.modify_date
     *
     * @return the value of oms_cart_item.modify_date
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.modify_date
     *
     * @param modifyDate the value for oms_cart_item.modify_date
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.delete_status
     *
     * @return the value of oms_cart_item.delete_status
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.delete_status
     *
     * @param deleteStatus the value for oms_cart_item.delete_status
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_category_id
     *
     * @return the value of oms_cart_item.product_category_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_category_id
     *
     * @param productCategoryId the value for oms_cart_item.product_category_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_brand
     *
     * @return the value of oms_cart_item.product_brand
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_brand
     *
     * @param productBrand the value for oms_cart_item.product_brand
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sn
     *
     * @return the value of oms_cart_item.product_sn
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sn
     *
     * @param productSn the value for oms_cart_item.product_sn
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_attr
     *
     * @return the value of oms_cart_item.product_attr
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public String getProductAttr() {
        return productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_attr
     *
     * @param productAttr the value for oms_cart_item.product_attr
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setProductAttr(String productAttr) {
        this.productAttr = productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", productSkuId=").append(productSkuId);
        sb.append(", memberId=").append(memberId);
        sb.append(", quantity=").append(quantity);
        sb.append(", price=").append(price);
        sb.append(", productPic=").append(productPic);
        sb.append(", productName=").append(productName);
        sb.append(", productSubTitle=").append(productSubTitle);
        sb.append(", productSkuCode=").append(productSkuCode);
        sb.append(", memberNickname=").append(memberNickname);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", productCategoryId=").append(productCategoryId);
        sb.append(", productBrand=").append(productBrand);
        sb.append(", productSn=").append(productSn);
        sb.append(", productAttr=").append(productAttr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}