package com.wggt.pojo;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   用户和标签关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_member_member_tag_relation
 */
public class UmsMemberMemberTagRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_member_tag_relation.id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_member_tag_relation.member_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_member_tag_relation.tag_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_member_tag_relation.id
     *
     * @return the value of ums_member_member_tag_relation.id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_member_tag_relation.id
     *
     * @param id the value for ums_member_member_tag_relation.id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_member_tag_relation.member_id
     *
     * @return the value of ums_member_member_tag_relation.member_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_member_tag_relation.member_id
     *
     * @param memberId the value for ums_member_member_tag_relation.member_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_member_tag_relation.tag_id
     *
     * @return the value of ums_member_member_tag_relation.tag_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_member_tag_relation.tag_id
     *
     * @param tagId the value for ums_member_member_tag_relation.tag_id
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Tue Apr 23 10:55:49 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", tagId=").append(tagId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}